name = "vantix-checkout"
main = "vantix_worker_COMPLETE.js"
compatibility_date = "2024-01-01"

[vars]
GOOGLE_SHEET_WEBHOOK_URL = "https://script.google.com/macros/s/AKfycbxGd-TzTIFXou9Cp7iOpq0qHKLDcTZsDqx9sjMuiNYaeD_kGTGcF7HYK57xfPZ_aM_A4w/exec"
TELEGRAM_BOT_TOKEN = "8478171743:AAGmYaPtMFh5yHWI-UQmInSlLuYNEcGFbXo"
TELEGRAM_CHAT_ID = "513307658"
BANKFUL_USERNAME = "vantixbio@gmail.com"
BANKFUL_PASSWORD = "Vantixbio@140"
BANKFUL_GATEWAY = "73922"
